version: '3.8'

services:
  web:
    build: .
    env_file:
      - .env
    volumes:
      - /secrets/credentials.json:/app/credentials.json
      - /secrets/token.pickle:/app/token.pickle
      - /secrets/dental-recep-adminsdk.json:/app/dental-recep-adminsdk.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3 